# Generated by Django 4.2.7 on 2023-12-17 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_app', '0005_alter_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firend',
            field=models.ManyToManyField(blank=True, related_name='user_firends', to=settings.AUTH_USER_MODEL),
        ),
    ]
