# Generated by Django 4.2.7 on 2023-12-02 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_reactioncomments_reactionposts_remove_likeposts_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_liked_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='reactionposts',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reactionposts',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReactionComments',
        ),
        migrations.DeleteModel(
            name='ReactionPosts',
        ),
    ]
