# Generated by Django 4.2.7 on 2023-12-17 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_viewposts_savedposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='posts.posts'),
        ),
        migrations.AlterField(
            model_name='likeposts',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='posts.posts'),
        ),
        migrations.AlterField(
            model_name='savedposts',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_saved', to='posts.posts'),
        ),
        migrations.AlterField(
            model_name='viewposts',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to='posts.posts'),
        ),
    ]
